// <auto-generated />
using System;
using E_mart_final_project.models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Emartfinalproject.Migrations
{
    [DbContext(typeof(EmartContext))]
    [Migration("20230222064318_fi")]
    partial class fi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_mart_final_project.models.CatMaster", b =>
                {
                    b.Property<int>("CatMasterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatMasterID"));

                    b.Property<string>("CatID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatImagPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("ProductMastersProductID")
                        .HasColumnType("int");

                    b.Property<string>("SubCatID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CatMasterID");

                    b.HasIndex("ProductMastersProductID");

                    b.ToTable("CatMaster");
                });

            modelBuilder.Entity("E_mart_final_project.models.ConfigMaster", b =>
                {
                    b.Property<int>("ConfigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigID"));

                    b.Property<string>("ConfigName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConfigID");

                    b.ToTable("ConfigMaster");
                });

            modelBuilder.Entity("E_mart_final_project.models.ProductDtlMaster", b =>
                {
                    b.Property<int>("ProductDtlID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductDtlID"));

                    b.Property<string>("ConfigDtl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConfigID")
                        .HasColumnType("int");

                    b.Property<int>("ConfigMastersConfigID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("ProductMastersProductID")
                        .HasColumnType("int");

                    b.HasKey("ProductDtlID");

                    b.HasIndex("ConfigMastersConfigID");

                    b.HasIndex("ProductMastersProductID");

                    b.ToTable("ProductDtlMaster");
                });

            modelBuilder.Entity("E_mart_final_project.models.ProductMaster", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<double>("CardHolderPrice")
                        .HasColumnType("float");

                    b.Property<int>("PointRedm")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductLongDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("ProductMaster");
                });

            modelBuilder.Entity("E_mart_final_project.models.CatMaster", b =>
                {
                    b.HasOne("E_mart_final_project.models.ProductMaster", "ProductMasters")
                        .WithMany("CatMasters")
                        .HasForeignKey("ProductMastersProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductMasters");
                });

            modelBuilder.Entity("E_mart_final_project.models.ProductDtlMaster", b =>
                {
                    b.HasOne("E_mart_final_project.models.ConfigMaster", "ConfigMasters")
                        .WithMany("ProductDtlMasters")
                        .HasForeignKey("ConfigMastersConfigID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_mart_final_project.models.ProductMaster", "ProductMasters")
                        .WithMany("ProductDtlMasters")
                        .HasForeignKey("ProductMastersProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigMasters");

                    b.Navigation("ProductMasters");
                });

            modelBuilder.Entity("E_mart_final_project.models.ConfigMaster", b =>
                {
                    b.Navigation("ProductDtlMasters");
                });

            modelBuilder.Entity("E_mart_final_project.models.ProductMaster", b =>
                {
                    b.Navigation("CatMasters");

                    b.Navigation("ProductDtlMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
